apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-airflow
  namespace: airflow
  labels:
    app: postgres-airflow
type: Opaque
data:
  POSTGRES_USER: YWlyZmxvdw==         # Base64 encoded value of 'airflow'
  POSTGRES_PASSWORD: YWlyZmxvd3Bhc3M=  # Base64 encoded value of 'airflowpass'