name: Deploy Airflow

on:
  workflow_call: {}

jobs:
  deploy_airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Deploy Airflow PostgreSQL
        run: |
          kubectl apply -f airflow_k8s/postgres_airflow/postgres_secret_airflow.yaml -n airflow
          kubectl apply -f airflow_k8s/postgres_airflow/postgres_pvc_airflow.yaml -n airflow
          kubectl apply -f airflow_k8s/postgres_airflow/postgres_stateful_airflow.yaml -n airflow

      - name: Create Airflow secrets
        run: |
          kubectl create secret generic airflow-postgres \
            --from-literal=connection=postgresql://airflow:airflowpass@postgres-airflow:5432/airflow_metastore \
            -n airflow || echo "Secret airflow-postgres already exists"
          kubectl create secret generic osds-webserver-secret \
            --from-literal="webserver-secret-key=$(python3 -c 'import secrets; print(secrets.token_hex(16))')" \
            -n airflow || echo "Secret osds-webserver-secret already exists"

      - name: Deploy Airflow PVC
        run: |
          kubectl apply -f airflow_k8s/airflow-pvc.yaml -n airflow

      - name: Install Airflow
        run: |
          helm repo add apache-airflow https://airflow.apache.org
          helm repo update
          helm upgrade --install airflow apache-airflow/airflow \
            --namespace airflow \
            --values airflow_k8s/airflow-values.yaml \
            --debug \
            --timeout 10m || echo "Airflow Helm release already exists"

      - name: Create Airflow-Spark ClusterRoleBinding
        run: |
          kubectl create clusterrolebinding default-admin \
            --clusterrole cluster-admin \
            --serviceaccount=airflow:airflow-worker \
            --namespace spark-apps || echo "ClusterRoleBinding already exists"
