name: Deploy Namespaces

on:
  workflow_call:  # Trigger when called by another workflow (like from `Deploy PostgreSQL to GKE`)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Kubernetes Namespaces
        run: |
          kubectl create namespace spark-apps || echo "Namespace spark-apps already exists"
          kubectl create namespace airflow || echo "Namespace airflow already exists"
          kubectl create namespace spark-operator || echo "Namespace spark-operator already exists"
          kubectl create namespace trino || echo "Namespace trino already exists"
          kubectl create namespace kafka || echo "Namespace kafka already exists"
          kubectl create namespace dbt || echo "Namespace dbt already exists"
          kubectl create namespace superset || echo "Namespace superset already exists"
