name: Deploy dbt

on:
  workflow_call: {}

jobs:
  deploy_airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create dbt ServiceAccount and ClusterRoleBinding
        run: |
          kubectl create serviceaccount dbt -n dbt || echo "ServiceAccount dbt already exists"
          kubectl create clusterrolebinding dbt-role-binding \
            --clusterrole=edit \
            --serviceaccount=dbt:dbt \
            --namespace=dbt || echo "ClusterRoleBinding dbt-role-binding already exists"