name: Deploy Thriftserver and Trino

on:
  workflow_call: {}

jobs:
  deploy_airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Add Trino Helm repository
        run: |
          helm repo add trino https://trinodb.github.io/charts
          helm repo update         

      - name: Install Trino
        run: |
          helm upgrade --install --values trino/values.yaml trino trino/trino -n trino   

      - name: Install Spark Thrift Server
        run: |
          kubectl apply -f spark8s/spark-thriftserver.yaml -n spark-apps