name: Deploy Spark

on:
  workflow_call: {}

jobs:
  deploy_spark:
    runs-on: ubuntu-latest
    steps:

      - name: Create ClusterRoleBinding
        run: |
          kubectl apply -f spark8s/spark_svc_account.yaml -n spark-apps    

      - name: Install Spark Operator
        run: |
          helm upgrade --install osds-release spark8s/spark-operator-1.1.27/spark-operator \
            -n spark-operator \
            --create-namespace \
            --wait \
            --timeout 2m

      - name: Create Postgres for Hive
        run: |
          kubectl apply -f spark8s/postgres_hive_ms/postgres_pvc_hive_ms.yaml -n spark-apps
          kubectl apply -f spark8s/postgres_hive_ms/postgres_secret_hive_ms.yaml -n spark-apps
          kubectl apply -f spark8s/postgres_hive_ms/postgres_stateful_hive_ms.yaml -n spark-apps

      - name: Apply Hive Metastore Configurations
        run: |
          kubectl apply -f spark8s/hive-metastore/hive-metastore-cgf.yaml -n spark-apps
          kubectl apply -f spark8s/hive-metastore/hive-metastore.yaml -n spark-apps
          kubectl apply -f spark8s/hive-metastore/hive-metastore-svc.yaml -n spark-apps
          kubectl apply -f spark8s/hive-metastore/hive-schema.yaml -n spark-apps   

      - name: Wait 3 minutes before deleting Hive Schema Pod
        run: |
          echo "Waiting for 3 minutes before deleting the Hive Schema Pod..."
          sleep 180  # Wait for 3 minutes

      - name: Delete Hive Schema Pod
        run: |
          kubectl delete -f spark8s/hive-metastore/hive-schema.yaml -n spark-apps