name: Deploy Superset

on:
  workflow_call: {}

jobs:
  deploy_airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Add Superset Helm repository
        run: |
          helm repo add superset https://apache.github.io/superset
          helm repo update

      - name: Install Superset
        run: |
          helm upgrade --install --values superset/superset-values.yaml \
            superset superset/superset -n superset --wait || echo "Superset Helm release already exists"
