name: Deploy PostgreSQL to GKE

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the main branch

env:
  CLUSTER_NAME: osd-k8s-cluster
  CLUSTER_ZONE: us-east1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install GKE Auth Plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --zone ${{ env.CLUSTER_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Create namespace spark-apps
        run: |
          kubectl create namespace spark-apps || echo "Namespace spark-apps already exists"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.3'  # Specify a version if needed

      - name: Install Spark Operator
        run: |
          helm repo add spark-operator https://kubeflow.github.io/spark-operator
          helm repo update
          helm install osd-release spark-operator/spark-operator \
            --namespace spark-operator \
            --create-namespace \
            --set sparkJobNamespace=spark-apps \   
            --set image.tag= v1beta2-1.6.0-3.5.0

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f spark8s/postgres_hive_ms/postgres_pvc_hive_ms.yaml -n spark-apps
          kubectl apply -f spark8s/postgres_hive_ms/postgres_secret_hive_ms.yaml -n spark-apps
          kubectl apply -f spark8s/postgres_hive_ms/postgres_stateful_hive_ms.yaml -n spark-apps

      - name: Verify PostgreSQL deployment
        run: |
          kubectl get pods -l app=postgres -n spark-apps
          kubectl get pvc -n spark-apps