name: Deploy Milan to GKE

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository to ensure that local files are available
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Use your custom action
      - name: Run setup action
        uses: ./.github/actions/setup
