name: Main Deployment Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggering
    inputs:
      deploy_setup:
        description: "Run Setup"
        required: false
        default: "false"
      deploy_spark:
        description: "Deploy Spark"
        required: false
        default: "false"
      deploy_airflow:
        description: "Deploy Airflow"
        required: false
        default: "false"
      deploy_kafka:
        description: "Deploy Kafka"
        required: false
        default: "false"
      deploy_superset:
        description: "Deploy Superset"
        required: false
        default: "false"
      deploy_sts_trino:
        description: "Deploy ThriftServer and Trino"
        required: false
        default: "false"

jobs:
  setup:
    name: Setup Environment
    if: ${{ github.event.inputs.deploy_setup == 'true' }}  # Conditional execution
    runs-on: ubuntu-latest
    steps:
      - name: Trigger setup
        uses: ./.github/workflows/setup.yml  # Refer to deploy_spark.yml directly, this will be triggered as a workflow


  deploy_spark:
    name: Deploy Spark
    needs: setup
    if: ${{ github.event.inputs.deploy_spark == 'true' }}  # Conditional execution
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy_spark workflow
        uses: ./.github/workflows/deploy_spark.yml  # Refer to deploy_spark.yml directly, this will be triggered as a workflow

  deploy_airflow:
    name: Deploy Airflow
    needs: setup
    if: ${{ github.event.inputs.deploy_airflow == 'true' }}  # Conditional execution
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy_airflow workflow
        uses: ./.github/workflows/deploy_airflow.yml  # Refer to deploy_airflow.yml directly

  deploy_kafka:
    name: Deploy Kafka
    needs: setup
    if: ${{ github.event.inputs.deploy_kafka == 'true' }}  # Conditional execution
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy_kafka workflow
        uses: ./.github/workflows/deploy_kafka.yml  # Refer to deploy_kafka.yml directly

  deploy_superset:
    name: Deploy Superset
    needs: setup
    if: ${{ github.event.inputs.deploy_superset == 'true' }}  # Conditional execution
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy_superset workflow
        uses: ./.github/workflows/deploy_superset.yml  # Refer to deploy_superset.yml directly

  deploy_sts_trino:
    name: Deploy ThriftServer and Trino
    needs: setup
    if: ${{ github.event.inputs.deploy_sts_trino == 'true' }}  # Conditional execution
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy_sts_trino workflow
        uses: ./.github/workflows/deploy_sts_trino.yml  # Refer to deploy_sts_trino.yml directly
