name: Deploy PostgreSQL to GKE

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the main branch

env:
  CLUSTER_NAME: osd-k8s-cluster
  CLUSTER_ZONE: us-east1

jobs:
  setup-cluster:
    uses: ./.github/workflows/setup-cluster.yml

  deploy-namespaces:
    needs: setup-cluster
    uses: ./.github/workflows/deploy-namespaces.yml
