name: Setup Cluster

on:
  workflow_call:  # Trigger when called by another workflow (like from `Deploy PostgreSQL to GKE`)


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

        env:
          CLUSTER_NAME: osd-k8s-cluster
          CLUSTER_ZONE: us-east1
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}  # Inject another secret as environment variable

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

        env:
          CLUSTER_NAME: osd-k8s-cluster
          CLUSTER_ZONE: us-east1
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}  # Inject another secret as environment variable

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install GKE Auth Plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --zone ${{ env.CLUSTER_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}
          
        env:
          CLUSTER_NAME: osd-k8s-cluster
          CLUSTER_ZONE: us-east1
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}  # Inject another secret as environment variable